import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import { CreateMember } from "../components/createMember";
import { CreateProposal } from "../components/createProposal";
import Navbar from "../components/navbar";
import { ProposalCard } from "../components/proposalCard";
import { ProposalList } from "../components/proposalList";
import { useData } from "../contexts/dataContext";
import styles from "../styles/Home.module.css";

export interface MarketProps {
  id: string;
  title: string;
  imageHash: string;
  totalAmount: string;
  totalYes: string;
  totalNo: string;
}

export default function Home() {
  const { isMember, isStakeholder } = useData();
  return (
    <div className={styles.container}>
      <Head>
        <title>Polymarket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {!isMember && <CreateMember />}
      {/* {isMember && <CreateProposal />} */}
      {isMember && <ProposalList />}
    </div>
  );
}
